### ISSUE TITLE
https://w3c.ink

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#10]
```yaml
name: W3C王三尺Blog
avatar: https://i.loli.net/2020/08/11/LUYOkP78adiBVtH.png
tags: [web, iot]
```
