### ISSUE TITLE
https://istaotao.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#11]
```yaml
name: 大涛子客栈
avatar: https://i.loli.net/2020/08/11/6inogC2hbYQ9a4z.jpg
tags: [前端, 摄影]
```
