### ISSUE TITLE
http://bgods.cn/blog

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#14]
```yaml
name: Bgods
avatar: https://img.vim-cn.com/3c/ce71eb91fb719ad8e326edfec955567fee59c4.png
tags: [Python]
```
