### ISSUE TITLE
https://sxyugao.top

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#15]
```yaml
name: YuGao's Blog
avatar: https://img.vim-cn.com/83/1989ac69e5e09b0a95355a26128a5a00bc14ef.png
tags: [Oier]
```
