### ISSUE TITLE
https://mjx.js.org

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#19]
```yaml
name: mjx’s blog
avatar: https://i.loli.net/2019/08/20/Y1ImSMrWHoZzXkJ.jpg
tags: [java, js]
desc: 
```
