### ISSUE TITLE
https://www.l-zhe.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#21]
```yaml
name: 人参地里的地瓜
avatar: https://img.vim-cn.com/6e/0ce62a6403bff39e1b4a797b58b0ea014a1bc5.jpg
tags: [念念不忘，必有回响]
desc: 
```
