### ISSUE TITLE
https://wuyongzhi.top

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#22]
```yaml
name: WuYongzhi·Blog
avatar: https://img.vim-cn.com/f1/f5df4933501bbd3dbd4ece70c9cb2a24dada01.jpg
tags: [海员, 轮机员]
desc: 
```
