### ISSUE TITLE
https://mcmohen.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#23]
```yaml
name: Mohen’s blog
avatar: https://img.vim-cn.com/d9/90133cbc21b46c765beb08a89ec4bc45194d5b.jpg
tags: [C++, 蒟蒻]
desc: 
```
