### ISSUE TITLE
https://stevenmhy.tk

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#24]
```yaml
name: Steven_MengのBlog
avatar: https://img.vim-cn.com/7e/7fa766615fc6e71d4fb78273983478d2caf433.png
tags: [蒟蒻, 二次元]
desc: 
```
