### ISSUE TITLE
https://sublimerui.top

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#27]
```yaml
name: 果子酱
avatar: https://img.vim-cn.com/fe/3c027725ff2d5872ebce8534d711885b27a8c1.jpg
tags: [二次元, Web, 嵌入式]
desc: 
```
