### ISSUE TITLE
https://www.hcl233.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#28]
```yaml
name: 纯洁的V笑
avatar: https://img.vim-cn.com/0a/65444d48b7ae9f0d61b602fd318c51c2248da9.png
tags: [全栈, java, python]
desc: 
```
