### ISSUE TITLE
https://www.jianshu.com/u/bd668c09cabf

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#3]
```yaml
name: LKY7748
avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@18.12.27/posts/friends/39e66e7d422a215a47162f44789d05375703e1.jpg
tags: [iOS, 和而泰]
```
