### ISSUE TITLE
https://chralpha.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#30]
```yaml
name: ChrAlpha
avatar: https://img.vim-cn.com/22/02cb77952f7ee9d802567f0d070dd7f8992fe2.jpg
tags: [技术控, 退役OIer]
desc: 
```
