### ISSUE TITLE
https://xugaoyi.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#33]
```yaml
name: Evan blog
avatar: https://i.loli.net/2020/02/08/vfmPQRpoV9AYxCt.jpg
tags: [web前端]
desc: 
```
