### ISSUE TITLE
https://linhk1606.github.io

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#34]
```yaml
title: Linhk1606
avatar: https://i.loli.net/2020/02/09/PN7I5RJfFtA93r2.png
keywords: [OIer]
description: 
screenshot: https://i.loli.net/2020/08/21/3PmGLCKicnfow1x.png
```
