### ISSUE TITLE
https://blog.darkcrane.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#38]
```yaml
name: Darkcrane
avatar: https://i.loli.net/2020/03/06/GVvLqH3oIfRB1M2.jpg
tags: [Java, Android]
desc: 
```
