### ISSUE TITLE
https://actuarygarden.cn

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#39]
```yaml
name: 精算后花园
avatar: https://i.loli.net/2020/03/12/YGKinyEuAcMzjTS.png
tags: [精算师考试]
desc: 
```
