### ISSUE TITLE
https://www.yinhanlei.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#4]
```yaml
name: 尹寒磊
avatar: https://i.loli.net/2020/08/11/OQ6SLUh9ZAfPr7m.jpg
tags: [标签1, 标签2]
```
