### ISSUE TITLE
https://mlxxs.github.io

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#40]
```yaml
name: lxxs
avatar: https://i.loli.net/2020/02/28/wGs1FJE8drgpomU.jpg
tags: [I pray to myself.]
desc: 
```
