### ISSUE TITLE
https://www.liizhi.cn

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#42]
```yaml
name: Chemlez
avatar: https://s1.ax1x.com/2020/03/13/8mvbCj.jpg
tags: [Java, Python, NLP]
desc: 
```
