### ISSUE TITLE
https://blog.yinuxy.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#43]
```yaml
name: YINUXY’S BLOG
avatar: https://cdn.jsdelivr.net/gh/InfiniteYinux/cloud@2.42/avatar/avatar.png
tags: [Python, 算法, 大数据]
desc: 
```
