### ISSUE TITLE
https://mrhuanhao.cn

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#45]
```yaml
name: Huanhao‘s Blog
avatar: https://cdn.jsdelivr.net/gh/kjhuanhao/blogcdn/avatar.jpg
tags: [Linux, web]
desc: 
```
