### ISSUE TITLE
https://blog.wztlink1013.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#46]
```yaml
name: 尼采般地抒情
avatar: https://cdn.jsdelivr.net/gh/wztlink1013/figure/blogbase/touxiang.jpg
tags: [总结技术，记录生活]
desc: 
```
