### ISSUE TITLE
https://www.weupgo.cn

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#50]
```yaml
name: 文歌的小站
avatar: https://www.weupgo.cn/wp-content/uploads/2020/01/1.jpg
tags: [人工智能, web]
desc: 
```
