### ISSUE TITLE
https://www.flexiston.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#51]
```yaml
name: Flexiston’s Notes
avatar: https://cdn.jsdelivr.net/gh/Flexiston/CDN/img/avatar.png
tags: [标签1, 标签2]
desc: 
```
