### ISSUE TITLE
https://colsrch.top

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#52]
```yaml
title: Colsrch
avatar: https://cdn.jsdelivr.net/gh/Colsrch/images/Colsrch/avatar.jpg
keywords: [C/C++, MFC]
description: 
screenshot: https://i.loli.net/2020/08/22/dFRWXm52OVu8qfK.png
```
