### ISSUE TITLE
https://hasaik.com

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#58]
```yaml
name: Xu’s Blog
avatar: https://hasaik.com/images/avatar.jpg
tags: [Java, 前端]
desc: 
```
