### ISSUE TITLE
https://lucifer.ren/blog/

### ISSUE THREAD

**Issue by azl397985856** [xaoxuu/friends#59]
```yaml
name: lucifer 的网络博客
avatar:https://tva1.sinaimg.cn/large/006tNbRwly1ga7ognflh9j30b40b4q3w.jpg
tags: [前端, 算法, 力扣]
desc:一个脑洞很大的程序员，Github 30K LeetCode 项目，公众号《脑洞前端》。
```
