### ISSUE TITLE
https://mark-thinkpad.gitee.io

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#6]
```yaml
name: Mark’s blog
avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@18.12.27/posts/friends/549026147d70e78d9cd24fbc43007468e62bbb.png
tags: [Linux, Python3]
```
