### ISSUE TITLE
https://www.antmoe.com/

### ISSUE THREAD

**Issue by sviptzk** [xaoxuu/friends#61]
```yaml
name: 小康博客
avatar: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@latest/avatar.jpg
tags: [Coder, Student]
desc: 一个收藏回忆与分享技术的地方！
```

- [ ] 我已经添加 `xaoxuu.com` 到友链中，我的友链页面是： https://
- [ x ] 我使用了 issue 作为友链源，源仓库是 https://gitee.com/antmoe/friend/issues/I1RCQ3
