### ISSUE TITLE
https://hasaik.com

### ISSUE THREAD

**Issue by XuxuGood** [xaoxuu/friends#66]
```yaml
title: Xu’s Blog
avatar: https://hasaik.com/images/avatar.jpg
url: https://hasaik.com
keywords: [JAVA, 前端]
description: 简单不先于复杂，而是在复杂之后！
screenshot: https://i.loli.net/2020/09/05/IabBq7hjepoLOuR.png
```

我的友链页： https://hasaik.com/links/
