### ISSUE TITLE
https://colsrch.top

### ISSUE THREAD

**Issue by Colsrch** [xaoxuu/friends#67]
```yaml
#### 必填项 ####
# 网站标题
title: Colsrch
# 网站描述
description: 愿多年以后，我可以酌一杯清酒，烂醉如泥，梦中回到我们的曾经。
# 网站截图
screenshot: https://7bu.top/2020/09/05/893e98a441d5f.png
# 网站链接
url: https://colsrch.top

#### 可选项 ####
# 作者头像链接
avatar: https://cdn.jsdelivr.net/gh/Colsrch/images/Colsrch/avatar.jpg
# 关键词，多个关键词用英文逗号和一个空格隔开，如 keywords: A, B
keywords: [C/C++, Web前端, Java, .NET, Linux, Android]
# 网站组别，如果同时属于多个组用英文逗号和一个空格隔开，如 group: 技术大佬, 学生
group: [技术大佬, 学生]
```

我的友链页： https://colsrch.top/friends/
