### ISSUE TITLE
https://writeblog.github.io

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#7]
```yaml
name: 搅拌糖
avatar: https://i.loli.net/2020/03/18/J2Ss8hQfdn9ma6c.jpg
tags: [PHP, Go, 爱心控]
```
