### ISSUE TITLE
https://shansan.top

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#8]
```yaml
name: Shan San
avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@18.12.27/posts/friends/b46f4c325becfd94c80ed55edbcb928e.jpg
tags: [螺蛳粉, C]
```
