### ISSUE TITLE
https://www.moonster.life

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/friends#9]
```yaml
name: 一去二三遥
avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@18.12.27/posts/friends/3c2e83f8da3d0822de6e69e8373a66f9501011.png
tags: [Java, 摄影]
```
